name: Bug report
description: Report a reproducible bug or regression.
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please include enough detail to reproduce it.
  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS + .NET SDK + app mode
      placeholder: "Windows 11, .NET 10.0.103, Web UI"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Run ...
        2. Open ...
        3. Click ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste relevant logs/errors or attach screenshots.
