namespace LocalTranscriber.Web.Transcription;

internal sealed record TranscriptionJobRequest(
    string JobId,
    string InputAudioPath,
    string InputChecksum,
    string Model,
    string Language,
    int MaxSegmentLength,
    bool EnableSpeakerLabels,
    int? SpeakerCount,
    int SpeakerSensitivity,
    double? SpeakerMinScoreGain,
    double? SpeakerMaxSwitchRate,
    double? SpeakerMinSeparation,
    int? SpeakerMinClusterSize,
    int? SpeakerMaxAutoSpeakers,
    double? SpeakerGlobalVarianceGate,
    double? SpeakerShortRunMergeSeconds,
    int FormatSensitivity,
    bool FormatStrictTranscript,
    double? FormatOverlapThreshold,
    int? FormatSummaryMinBullets,
    int? FormatSummaryMaxBullets,
    bool FormatIncludeActionItems,
    double? FormatTemperature,
    int? FormatMaxTokens,
    double? FormatLocalBigGapSeconds,
    double? FormatLocalSmallGapSeconds,
    TranscriptionFormatProvider FormatProvider,
    string OllamaUri,
    string OllamaModel,
    string HuggingFaceEndpoint,
    string HuggingFaceModel,
    string? HuggingFaceApiKey
);
